url      : https://training.sdsc.edu     # the base hostname & protocol for your site 
baseurl: 
webinarurl :  https://github.com/sdsc-hpc-training/webinars
bootcampurl :  https://github.com/sdsc-hpc-training/tscc-tutorials
abouturl :   /about
blogurl :   /blog
name: Mary Thomas, SDSC Training
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

